--1.DISPLAY ENAME,DEPTNAME IN PLSQL FOR EMPLOYEES

SET SERVEROUTPUT ON
DECLARE
VAR3 VARCHAR2(100);
CURSOR C1 IS
SELECT FIRST_NAME,DEPARTMENT_NAME FROM EMPLOYEES JOIN DEPARTMENTS ON EMPLOYEES.DEPARTMENT_ID=DEPARTMENTS.DEPARTMENT_ID;
BEGIN
FOR I IN C1
LOOP
DBMS_OUTPUT.PUT_LINE(I.FIRST_NAME || ' ' || I.DEPARTMENT_NAME);
END LOOP;
END;


--2.DISPLAY EMPID,JOB_ID,SALARY OF 'STEPHEN' IN PLSQL

SET SERVEROUTPUT ON
DECLARE
VAR1 VARCHAR2(100);
VAR2 VARCHAR2(10);
VAR3 VARCHAR2(10);
BEGIN
SELECT EMPLOYEE_ID,JOB_ID,SALARY INTO VAR1,VAR2,VAR3 FROM EMPLOYEES WHERE FIRST_NAME='Stephen';
DBMS_OUTPUT.PUT_LINE(VAR1);
DBMS_OUTPUT.PUT_LINE(VAR2);
DBMS_OUTPUT.PUT_LINE(VAR3);
END;

--3.DISPLAY TOP 10 SALARIES IN EMPLOYEE TABLE

SET SERVEROUTPUT ON
DECLARE
VAR1 VARCHAR2(10);
CURSOR C1 IS
SELECT SALARY FROM (SELECT DISTINCT SALARY FROM EMPLOYEES ORDER BY SALARY DESC) WHERE ROWNUM<=10; 
BEGIN
FOR I IN C1
LOOP
DBMS_OUTPUT.PUT_LINE(I.SALARY);
END LOOP;
END;

--4.CREATE A PROCEDURE TO ADD,SUBTRACT,MULTIPLY,DIVIDE TWO NUMBERS

CREATE OR REPLACE PROCEDURE PRO_ARITH_OPR(V1 IN NUMBER,V2 IN NUMBER)
AS
V3 NUMBER;
V4 NUMBER;
V5 NUMBER;
V6 NUMBER;
BEGIN
V3:=V1+V2;
V4:=V1-V2;
V5:=V1*V2;
V6:=V1/V2;
DBMS_OUTPUT.PUT_LINE(V3);
DBMS_OUTPUT.PUT_LINE(V4);
DBMS_OUTPUT.PUT_LINE(V5);
DBMS_OUTPUT.PUT_LINE(V6);
END;
EXEC PRO_ARITH_OPR(100,50);
